/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package composicoestcpplanilha.Janelas;

import composicoestcpplanilha.Classes.Constantes;
import composicoestcpplanilha.Classes.Principal;
import composicoestcpplanilha.Suporte.NetworkInfo;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.net.SocketException;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;

/**
 *
 * @author Milene
 */
public class JanelaSerialKey extends javax.swing.JFrame {

  
  
    /**
     * Creates new form JanelaSerialKey
     */
    public JanelaSerialKey() {
        initComponents();
        this.txtBoxHash.setEditable(false);
    }

    public void setTxtBoxHash(String txtBoxHash) {
        this.txtBoxHash.setText(txtBoxHash); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBoxHash = new javax.swing.JTextField();
        txtBoxSerial = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnHashOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Validação");

        txtBoxHash.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtBoxSerial.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBoxSerial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBoxSerialActionPerformed(evt);
            }
        });

        jLabel1.setText("Hash");

        jLabel2.setText("Serial");

        btnHashOK.setText("OK");
        btnHashOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHashOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(txtBoxSerial, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
                            .addComponent(txtBoxHash)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(btnHashOK, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBoxHash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBoxSerial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnHashOK)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHashOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHashOKActionPerformed
        // TODO add your handling code here:
        String [] serial = txtBoxSerial.getText().split("-");
        
        try {
            boolean teste = NetworkInfo.verificarSerial(serial);
            
            if(teste){
                FileWriter StrW = new FileWriter(new File(Constantes.MISC_HASH));

                    StrW.write(txtBoxSerial.getText());
                    StrW.close();
                    this.dispose();
                    Principal.programa();
                    
            }
            
        } catch (SocketException ex) {
            Logger.getLogger(JanelaSerialKey.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnknownHostException ex) {
            Logger.getLogger(JanelaSerialKey.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(JanelaSerialKey.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnHashOKActionPerformed

    private void txtBoxSerialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBoxSerialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBoxSerialActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHashOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtBoxHash;
    private javax.swing.JTextField txtBoxSerial;
    // End of variables declaration//GEN-END:variables
}
