/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package composicoestcpplanilha.Janelas;

import composicoestcpplanilha.Classes.ConexaoCSV;
import composicoestcpplanilha.Classes.Constantes;
import composicoestcpplanilha.Classes.CriarTabela;
import composicoestcpplanilha.Suporte.TrocarPosicao;
import java.util.ArrayList;
import javax.swing.JTable;

/**
 *
 * @author Milene
 */
public class JanelaTrocaIdPrincipal extends javax.swing.JFrame {

    private JanelaPrincipal janelaPrincipal;
    private ConexaoCSV principal = new ConexaoCSV(Constantes.DESPESAS_DIRETASP);
    private ConexaoCSV secundario = new ConexaoCSV(Constantes.DESPESAS_DIRETASS);
//    private ArrayList<String> listPrincipal = principal.readCsvFile();
//    private ArrayList<String> listSecundaria = secundario.readCsvFile();

    private JTable tabela;
    private String[] colunasTabela;

    public String idPrinc = "";

    public void setIdPrinc(String idPrinc) {
        this.idPrinc = idPrinc;
    }

    private int id1;
    private int id2;

    /**
     * Creates new form JanelaTrocaIdPrincipal
     */
    private JanelaTrocaIdPrincipal() {
        

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaQuantitativos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaQuantitativos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaQuantitativos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaQuantitativos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        initComponents();

        this.setLocationRelativeTo(null);

    }

    public JanelaTrocaIdPrincipal(JanelaPrincipal janelaPrincipal, JTable tabela, String[] colunasTabela) {
        this();
        this.janelaPrincipal = janelaPrincipal;
        this.colunasTabela = colunasTabela;
        this.tabela = tabela;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnOK = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtboxId1 = new javax.swing.JFormattedTextField();
        txtboxId2 = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Alteração de Posição");
        setResizable(false);

        jLabel1.setText("ID 1:");

        jLabel2.setText("ID 2:");

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtboxId1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        txtboxId2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtboxId1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtboxId2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnOK, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnOK)
                    .addComponent(txtboxId1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnCancelar)
                    .addComponent(txtboxId2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();

        janelaPrincipal.setEnabled(true);
        janelaPrincipal.toFront();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // Executar mudança de posição
        id1 = Integer.parseInt(txtboxId1.getText());
        id2 = Integer.parseInt(txtboxId2.getText());
        TrocarPosicao.Principal(id1, id2);
        if (idPrinc.isEmpty()) {
            TrocarPosicao.Secundario(id1, id2);
        } else {
            TrocarPosicao.Secundario(idPrinc, id1, id2);
        }

        this.dispose();
        janelaPrincipal.setEnabled(true);
        janelaPrincipal.toFront();

        CriarTabela tabelaServicoPrincipal = new CriarTabela(tabela, colunasTabela, principal);
        tabelaServicoPrincipal.criarTabelaServicoPrimario();


    }//GEN-LAST:event_btnOKActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JFormattedTextField txtboxId1;
    private javax.swing.JFormattedTextField txtboxId2;
    // End of variables declaration//GEN-END:variables

}
